import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForTimeout(1000);
await page.screenshot({path:'outputs/desktop-empty.png'});
await page.getByRole('button',{name:'삼각형 추가',exact:true}).click();
await page.getByRole('button',{name:'복제',exact:true}).click();
await page.getByRole('button',{name:'작품 분석',exact:true}).click();
await page.screenshot({path:'outputs/desktop-analysis.png'});
await page.getByRole('button',{name:'분석 닫기'}).click();
await page.keyboard.press('Control+a');
await page.getByRole('button',{name:'그룹',exact:true}).click();
await page.getByRole('button',{name:'그룹 해제',exact:true}).waitFor();
await page.getByRole('button',{name:'그룹 해제',exact:true}).click();
await page.getByRole('button',{name:'작품 저장',exact:true}).click();
await page.screenshot({path:'outputs/export-dialog.png'});
const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/작품만 저장 아트보드/}).click();const download=await downloadEvent;await download.saveAs('outputs/qa-artwork.png');
await page.getByRole('button',{name:'더보기',exact:true}).click();
const jsonEvent=page.waitForEvent('download');await page.getByRole('button',{name:'프로젝트 저장',exact:true}).click();await (await jsonEvent).saveAs('work/qa-project.json');
await page.getByRole('button',{name:'더보기',exact:true}).click();await page.getByRole('button',{name:'모두 지우기',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'모두 지우기',exact:true}).click();
await page.getByText('세 개의 각, 무한한 상상').waitFor();await page.getByRole('button',{name:'실행 취소',exact:true}).click();
assert.equal(await page.getByText('2개의 삼각형',{exact:true}).count(),1);
await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(400);await page.screenshot({path:'outputs/tablet-editor.png'});
await page.locator('input[type=file]').setInputFiles('work/qa-project.json');
await page.waitForTimeout(900);await page.reload();await page.getByRole('dialog').getByRole('button',{name:'이어서 만들기'}).click();assert.equal(await page.getByText('2개의 삼각형',{exact:true}).count(),1);
assert.deepEqual(errors,[]);console.log('PASS: desktop/tablet screenshots, create/duplicate/group/ungroup, PNG/JSON, clear/undo, load/autosave; no browser errors');
await browser.close();
