import { useEffect,useMemo,useRef,useState } from 'react';
import { Undo2,Redo2,MoreHorizontal,BarChart3,Download,Triangle as TriangleIcon,MousePointer2,Scan,Magnet,ChevronRight } from 'lucide-react';
import { Creator } from './components/Creator';
import { Analysis } from './components/Analysis';
import { Modal } from './components/Modal';
import { SelectionToolbar } from './components/SelectionToolbar';
import { Artboard } from './canvas/Artboard';
import { emptyProject,makeTriangle,type Triangle,type Filter,type Project } from './lib/model';
import type { Point } from './lib/geometry';
import { useEditor,duplicate } from './store/editor';
import { parseProject,serializeProject,download } from './lib/projectFile';
import { exportArtwork } from './lib/exportArtwork';
import { getTriangleProperties } from './lib/classification';
import { initializeAnalytics,trackEvent } from './lib/analytics';
const BACKUP='triangle-art-studio-v1';
function readBackup(){try {const raw=localStorage.getItem(BACKUP);const p=raw?parseProject(raw):null;return p?.triangles.length?p:null;}catch{return null;}}
export default function App() {
  const editor=useEditor(emptyProject()),{project,change}=editor;
  const [selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState<Filter>(null),[analysis,setAnalysis]=useState(false),[more,setMore]=useState(false),[multi,setMulti]=useState(false),[dialog,setDialog]=useState<'export'|'help'|'clear'|null>(null),[transparent,setTransparent]=useState(false),[message,setMessage]=useState(''),[backup,setBackup]=useState<Project|null>(readBackup),[saving,setSaving]=useState(false);
  const input=useRef<HTMLInputElement>(null),clipboard=useRef<Triangle[]>([]),menu=useRef<HTMLDivElement>(null),board=useRef<HTMLDivElement>(null);
  const selection=useMemo(()=>project.triangles.filter(t=>selected.includes(t.id)),[project.triangles,selected]);
  useEffect(()=>{if(backup)return;const timer=setTimeout(()=>{try{localStorage.setItem(BACKUP,serializeProject(project));}catch{setMessage('이 브라우저에서는 자동 백업이 어려워요. 프로젝트 파일로 저장해 주세요.');}},650);return ()=>clearTimeout(timer);},[project,backup]);
  useEffect(()=>{setSelected(s=>s.filter(id=>project.triangles.some(t=>t.id===id)));},[project.triangles]);
  useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),5000);return ()=>clearTimeout(t);},[message]);
  useEffect(()=>{if(!more)return;const handler=(e:PointerEvent)=>{if(!menu.current?.contains(e.target as Node))setMore(false);};document.addEventListener('pointerdown',handler);return ()=>document.removeEventListener('pointerdown',handler);},[more]);
  useEffect(()=>{initializeAnalytics();},[]);
  function paste(items:Triangle[]) {const copies=duplicate(items);change(p=>({...p,triangles:[...p.triangles,...copies]}));setSelected(copies.map(t=>t.id));}
  function createTriangle(a:number,b:number,fill:string,method:'button'|'drag',pos?:Point) {
    const t=makeTriangle(a,b,fill,project.triangles.length,pos);
    change(p=>({...p,triangles:[...p.triangles,t]}));
    setSelected([t.id]);
    const props=getTriangleProperties(a,b);
    trackEvent('triangle_created',{method,angle_type:props.angleType,is_isosceles:props.isIsosceles,is_equilateral:props.isEquilateral,mode:project.mode});
  }
  function action(type:string) {
    if(type==='duplicate'){paste(selection);return;}
    const groupId=crypto.randomUUID();change(p=>{let triangles=p.triangles;
      if(type==='delete')triangles=triangles.filter(t=>!selected.includes(t.id));
      if(type==='group'||type==='ungroup')triangles=triangles.map(t=>selected.includes(t.id)?{...t,groupId:type==='group'?groupId:undefined}:t);
      if(type==='forward'||type==='backward'){triangles=[...triangles];if(type==='forward'){for(let i=triangles.length-2;i>=0;i--)if(selected.includes(triangles[i].id)&&!selected.includes(triangles[i+1].id))[triangles[i],triangles[i+1]]=[triangles[i+1],triangles[i]];}else for(let i=1;i<triangles.length;i++)if(selected.includes(triangles[i].id)&&!selected.includes(triangles[i-1].id))[triangles[i],triangles[i-1]]=[triangles[i-1],triangles[i]];}
      return {...p,triangles};});
  }
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,dialog')||backup||dialog)return;const cmd=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(cmd&&['z','y','c','v','a','d'].includes(k)){e.preventDefault();if(k==='z')e.shiftKey?editor.redo():editor.undo();if(k==='y')editor.redo();if(k==='c')clipboard.current=structuredClone(selection);if(k==='v')paste(clipboard.current);if(k==='d')paste(selection);if(k==='a')setSelected(project.triangles.map(t=>t.id));}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();action('delete');}if(e.key==='Escape'){setSelected([]);setFilter(null);setMore(false);}};window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key);});
  async function load(file?:File){if(!file)return;try{if(file.size>5_000_000)throw new Error('파일이 너무 커요. 5MB 이하 프로젝트를 선택해 주세요.');const p=parseProject(await file.text());change(()=>p);setSelected([]);setFilter(null);setMessage('프로젝트를 불러왔어요.');trackEvent('project_loaded');}catch(e){setMessage(e instanceof Error?e.message:'파일을 읽을 수 없어요.');}if(input.current)input.current.value='';}
  async function saveImage(card:boolean){setSaving(true);try{await exportArtwork(project,card,transparent);setDialog(null);setMessage('작품 이미지를 저장했어요.');trackEvent('artwork_exported',{export_type:card?'artwork_card':'artwork',triangle_count:project.triangles.length});}catch{setMessage('저장하지 못했어요. 다시 시도해 주세요.');}finally{setSaving(false);}}
  return <div className="app"><header><div className="brand"><div className="brand-mark"><TriangleIcon size={25}/></div><div><h1>삼각형, 예술을 그리다<span>2.0</span></h1><p>4학년 수학 · 삼각형 폴리곤 아트</p></div></div><div className="history"><button title="실행 취소 (Ctrl+Z)" aria-label="실행 취소" disabled={!editor.canUndo} onClick={editor.undo}><Undo2 size={19}/></button><button title="다시 실행 (Ctrl+Shift+Z)" aria-label="다시 실행" disabled={!editor.canRedo} onClick={editor.redo}><Redo2 size={19}/></button></div><div className="mode" aria-label="창작 모드">{(['textbook','free'] as const).map(mode=><button key={mode} aria-pressed={project.mode===mode} className={project.mode===mode?'active':''} onClick={()=>{if(mode!==project.mode)trackEvent('mode_changed',{mode});change(p=>({...p,mode}));}}>{mode==='free'?'자유 창작':'교과서 활동'}</button>)}</div><div className="header-actions"><button className={analysis?'outline active':'outline'} onClick={()=>{const opening=!analysis;setAnalysis(opening);if(!opening)setFilter(null);if(opening)trackEvent('analysis_opened',{triangle_count:project.triangles.length});}}><BarChart3 size={17}/><span>작품 분석</span></button><button className="primary" onClick={()=>setDialog('export')}><Download size={17}/><span>작품 저장</span></button><div className="more" ref={menu}><button aria-label="더보기" aria-expanded={more} onClick={()=>setMore(!more)}><MoreHorizontal size={23}/></button>{more&&<div className="menu"><button onClick={()=>{download(new Blob([serializeProject(project)],{type:'application/json'}),'triangle-project.json');trackEvent('project_saved');setMore(false);}}>프로젝트 저장</button><button onClick={()=>{input.current?.click();setMore(false);}}>프로젝트 불러오기</button><button onClick={()=>change(p=>({...p,settings:{...p.settings,snap:!p.settings.snap}}))}>꼭짓점 스냅 {project.settings.snap?'ON':'OFF'}</button><button onClick={()=>{setDialog('help');trackEvent('help_opened');setMore(false);}}>사용방법</button><button className="danger" onClick={()=>{setDialog('clear');setMore(false);}}>모두 지우기</button></div>}</div></div></header>
    <main><Creator mode={project.mode} onAdd={createTriangle} boardRef={board}/><section className="workspace" aria-label="작품 제작 공간"><div className="workspace-top"><div><span className="eyebrow">02 / CREATE</span><h2>나의 아트보드 <span>{project.triangles.length}개의 삼각형</span></h2></div><div className="canvas-tools"><button title="선택 도구" aria-label="선택 도구" aria-pressed={!multi} className={!multi?'active':''} onClick={()=>setMulti(false)}><MousePointer2 size={17}/></button><button title="여러 개 선택" aria-label="여러 개 선택" aria-pressed={multi} className={multi?'active':''} onClick={()=>setMulti(!multi)}><Scan size={18}/></button></div></div><div className="canvas-area">{!!selection.length&&<SelectionToolbar count={selection.length} grouped={!!selection[0]?.groupId&&selection.every(t=>t.groupId===selection[0].groupId)} fill={selection[0].fill} onAction={action} onColor={fill=>change(p=>({...p,triangles:p.triangles.map(t=>selected.includes(t.id)?{...t,fill}:t)}))}/>}<Artboard triangles={project.triangles} selected={selected} setSelected={setSelected} onUpdate={triangles=>change(p=>({...p,triangles}))} filter={filter} snap={project.settings.snap} multi={multi} boardRef={board}/></div><footer><span><Magnet size={14}/>꼭짓점 스냅 {project.settings.snap?'켜짐':'꺼짐'}</span><span className="canvas-hint">드래그로 이동 · 모서리로 크기 조절 · 위 손잡이로 회전</span><span>1200 × 800</span></footer>{filter&&<button className="filter-notice" onClick={()=>setFilter(null)}>분류를 강조해서 보고 있어요 <span>전체 보기 ×</span></button>}</section>{analysis&&<Analysis triangles={project.triangles} filter={filter} setFilter={setFilter} onClose={()=>{setAnalysis(false);setFilter(null);}}/>}</main>
    <div className="narrow-notice">더 넓은 화면에서 사용하면 편리해요.</div><input ref={input} hidden type="file" accept=".json,application/json" onChange={e=>load(e.target.files?.[0])}/>{message&&<div className="toast" role="status">{message}</div>}
    {dialog==='export'&&<Modal title="작품 저장" onClose={()=>setDialog(null)}><p className="muted">완성한 작품을 고해상도 PNG로 간직해요.</p><button className="export-option" disabled={saving} onClick={()=>saveImage(false)}><div className="export-icon"><TriangleIcon/></div><span><b>작품만 저장</b><small>아트보드만 깔끔하게 · 2400 × 1600</small></span><ChevronRight size={18}/></button><button className="export-option" disabled={saving} onClick={()=>saveImage(true)}><div className="export-icon"><BarChart3/></div><span><b>작품 카드 저장</b><small>내 작품과 수학 분석을 한 장에</small></span><ChevronRight size={18}/></button><label className="check"><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/>작품만 저장할 때 배경을 투명하게</label></Modal>}
    {dialog==='help'&&<Modal title="세 개의 각으로 시작해요" onClose={()=>setDialog(null)}><ol className="help-list">{['각을 조절해 삼각형을 만들어요.','삼각형을 캔버스에 추가해요.','움직이고 돌리며 작품을 만들어요.','작품 분석에서 사용한 삼각형을 살펴봐요.','완성한 작품을 이미지로 저장해요.'].map(t=><li key={t}>{t}</li>)}</ol><p className="note">Shift + 클릭 또는 빈 곳 드래그: 여러 개 선택<br/>터치: ‘여러 개 선택’ 도구를 누르고 삼각형을 탭<br/>Ctrl/Cmd + Z: 실행 취소 · Shift + Z: 다시 실행<br/>Ctrl/Cmd + C / V: 복사 / 붙여넣기 · Delete: 삭제<br/>그룹은 함께 움직이고 같은 비율로 커져요.</p></Modal>}
    {dialog==='clear'&&<Modal title="모두 지울까요?" onClose={()=>setDialog(null)}><p>아트보드의 삼각형을 모두 지워요. 실행 취소로 되돌릴 수 있어요.</p><div className="dialog-actions"><button className="outline" onClick={()=>setDialog(null)}>취소</button><button className="danger-fill" onClick={()=>{change(p=>({...p,triangles:[]}));setDialog(null);}}>모두 지우기</button></div></Modal>}
    {backup&&<Modal title="이전 작업을 이어서 할까요?" onClose={()=>setBackup(null)}><p>이 브라우저에 저장된 삼각형 {backup.triangles.length}개의 작업이 있어요.</p><div className="dialog-actions"><button className="outline" onClick={()=>setBackup(null)}>새로 시작</button><button className="primary" onClick={()=>{change(()=>backup);setBackup(null);}}>이어서 만들기</button></div></Modal>}
  </div>;
}

